// <auto-generated />
using EmployeeManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 4,
                            Email = "vipin@accops.com",
                            Name = "Vipin"
                        },
                        new
                        {
                            Id = 2,
                            Department = 5,
                            Email = "rajiv@accops.com",
                            Name = "Rajiv"
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            Email = "dev@accops.com",
                            Name = "Dev"
                        },
                        new
                        {
                            Id = 4,
                            Department = 5,
                            Email = "kartik@accops.com",
                            Name = "Kartik"
                        },
                        new
                        {
                            Id = 5,
                            Department = 1,
                            Email = "samarth@accops.com",
                            Name = "Samarth"
                        },
                        new
                        {
                            Id = 6,
                            Department = 3,
                            Email = "akash@accops.com",
                            Name = "Akash"
                        },
                        new
                        {
                            Id = 7,
                            Department = 2,
                            Email = "arjun@accops.com",
                            Name = "Arjun"
                        },
                        new
                        {
                            Id = 8,
                            Department = 4,
                            Email = "risabh.rai@accops.com",
                            Name = "Risabh Rai"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
